name: Generate MAIN.CSV and README

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v3

    # Run using Python 3.8 for consistency and aiohttp
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies
        architecture: 'x64'

    # Install dependencies with `pip`
    - name: Install requirements
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r requirements.txt
        
    # Generate all statistics images
    - name: Generate data
      run: |
        python3 --version
        python3 setupdata.py
  
    - name: commit files
      run: |
        git config --local user.email "jmrplens@gmail.com"
        git config --local user.name "jmrplens"
        git add -A
        git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
    - name: Pushing to the protected branch 'protected'
      uses: CasperWA/push-protected@v2
      with:
        token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
        branch: main
        unprotect_reviews: true
    
